# Generated by Django 4.2 on 2023-04-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_competition_games_alter_competition_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='level',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
