# Generated by Django 4.2 on 2023-04-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_competition_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='looser',
        ),
    ]
